project:
  type: website

website:
  description: "Molecular modeling, GROMACS, and Python tutorials."
  site-url: https://bogrum.xyz # you must change this appropriately for RSS feeds to work properly
  title: "i-dev-biodynamics"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bogrum
      - icon: bsky
        href: https://bsky.app/profile/i-dev-dynamics.bsky.social
format:
  html:

    theme: 
      light: flatly
      dark: cyborg
    css: styles.css
    toc: true
    number-sections: true
    code-fold: false



